-- migrate .vimrc
vim.cmd([[
    "" General
    set number	" Show line numbers
    set linebreak	" Break lines at word (requires Wrap lines)
    set showbreak=+++	" Wrap-broken line prefix
    set textwidth=100	" Line wrap (number of cols)
    set showmatch	" Highlight matching brace
    set visualbell	" Use visual bell (no beeping)
     
    set hlsearch	" Highlight all search results
    set smartcase	" Enable smart-case search
    set ignorecase	" Always case-insensitive
    set incsearch	" Searches for strings incrementally
     
    set autoindent	" Auto-indent new lines
    set expandtab	" Use spaces instead of tabs
    set shiftwidth=4	" Number of auto-indent spaces
    set smartindent	" Enable smart-indent
    set smarttab	" Enable smart-tabs
    set softtabstop=4	" Number of spaces per Tab
     
    "" Advanced
    set ruler	" Show row and column ruler information
     
    set undolevels=1000	" Number of undo levels
    set backspace=indent,eol,start	" Backspace behaviour
     
    set noro        " default to not readonly in VimDiff
     
    let @p='i ^[p'  "put with space before
    set clipboard=unnamedplus   "global clipboard

    let mapleader = ',' "map leader key
    nnoremap <Space> i<Space><Right><ESC> "key reymap for space in normal mode
    "" Generated by VimConfig.com
]])

-- install lazy plugin manager https://github.com/folke/lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

local opts={}
require("lazy").setup("plugins", opts)



