# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E1C6BD
background         #0D0A0A
cursor             #E1C6BD

active_tab_foreground     #0D0A0A
active_tab_background     #E1C6BD
inactive_tab_foreground   #E1C6BD
inactive_tab_background   #0D0A0A

active_border_color   #E1C6BD
inactive_border_color #0D0A0A
bell_border_color     #0F0C08

color0      #373535
color1		#0F0C08
color2		#0E281C
color3		#663320
color4		#0E553A
color5		#0E6142
color6		#804533
color7		#CCA599
color8		#8F746B
color9		#14100B
color10		#133525
color11		#88442B
color12		#12724E
color13		#128158
color14		#AA5C44
color15		#CCA599
