[[mgr.prepend_keymap]]
on   = [ "l" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = [ "C" ]
run  = "plugin ouch"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = [ ".", "h" ]
run  = "hidden toggle"
desc = "Toggle hidden files"

[[mgr.prepend_keymap]]
on   = [ ".", "m" ]
run  = "linemode mtime"
desc = "Linemode: mtime"

[[mgr.prepend_keymap]]
on   = [ ".", "s" ]
run  = "linemode size"
desc = "Linemode: size"

[[mgr.prepend_keymap]]
on   = [ ".", "p" ]
run  = "linemode permissions"
desc = "Linemode: permissions"

[[mgr.prepend_keymap]]
on = ["1"]
run = "plugin relative-motions 1"

[[mgr.prepend_keymap]]
on = ["2"]
run = "plugin relative-motions 2"

[[mgr.prepend_keymap]]
on = ["3"]
run = "plugin relative-motions 3"

[[mgr.prepend_keymap]]
on = ["4"]
run = "plugin relative-motions 4"

[[mgr.prepend_keymap]]
on = ["5"]
run = "plugin relative-motions 5"

[[mgr.prepend_keymap]]
on = ["6"]
run = "plugin relative-motions 6"

[[mgr.prepend_keymap]]
on = ["7"]
run = "plugin relative-motions 7"

[[mgr.prepend_keymap]]
on = ["8"]
run = "plugin relative-motions 8"

[[mgr.prepend_keymap]]
on = ["9"]
run = "plugin relative-motions 9"
