return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()

        local config = require("nvim-treesitter.configs")
        config.setup({
            ensure_installed = { 
                "rust", 
                "python", 
                "c", 
                "lua", 
                "vim", 
                "vimdoc", 
                "javascript", 
                "html", 
                "bash", 
                "cmake", 
                "cpp", 
                "css", 
                "cuda", 
                "diff", 
                "dockerfile", 
                "dot", 
                "git_config", 
                "git_rebase", 
                "gitattributes",
                "gitcommit",
                "gitignore",
                "glsl",
                "gnuplot",
                "graphql",
                "helm",
                "hlsl",
                "ini",
                "jq",
                "json",
                "json5",
                "julia",
        --        "latex",
                "llvm",
                "markdown",
                "make",
                "mermaid",
        --        "mlir",
                "ninja",
                "nix",
                "objdump",
                "promql",
                "proto",
                "sparql",
                "sql",
                "terraform",
                "tmux",
                "toml",
                "typescript",
                "xml",
                "yaml"
            },
            sync_install = false,
            highlight = { enable = true },
            indent = { enable = true },  
        })
    end

} -- treesitter https://github.com/nvim-treesitter/nvim-treesitter/wiki/Installation
